"""
Program inputs: *.dat files generated by MPMS3.
Parameters: folderpath, subfolder, headers
Program output: *_Sweep-Split.dat files with (H,M) downsweep and (H,M) upsweep in 4 columns in a subfolder.
"""
folderpath = 'C:/Users/mishra/Downloads/MPMS3' #Location of inputs
subfolder = 'MH_Sweep-Split' #Subfolder name for outputs
headers = 45 #Number of headers in MPMS3 data file i.e lines to ignore when importing

import numpy as np #For importing and manipulating data
import os #For changing and creating folders
import shutil #For deleting folders already present
import glob #For batch importing files

os.chdir(folderpath)#Changes directory to folderpath
shutil.rmtree(subfolder, ignore_errors=True) #Deletes subfolder if already present
os.mkdir(subfolder) #Creates subfolder
files = glob.glob('*.dat') #Imports filenames with .dat extension
filecount = len(files)  #Counts number of files in folderpath

print(f'The following {filecount} files will be split into downsweep and upsweep:')
print(files) #Prints name of all files to be processed

for i in range(filecount): #Loops through all files
    #MH Data splitting
    data_raw = np.loadtxt(files[i], delimiter=',', skiprows=headers, usecols=[3,4]) #Loads column 3 (H) and 4 (M) from MPMS3 .dat files
    split = int((len(data_raw[:,0])-1)/2) #Finds the length of data and splits the number by 2.
    H_down = data_raw[0:split+1,0] #Downsweep H data
    M_down = data_raw[0:split+1,1] #Downsweep M data
    H_up = data_raw[split:,0] #Upsweep H data
    M_up = data_raw[split:,1] #Upsweep M data
    #Save split MH data in subdirectory
    data = np.column_stack((H_down, M_down, H_up, M_up)) #Makes column out of downsweep and upsweep MH.
    filename = ''.join(files[i].split())[:-4] #Removes last 4 characters (.dat) from filename.
    filepath = f'{folderpath}/{subfolder}/{filename}_MH_Sweep-Split.dat' #Creates name and location of output
    np.savetxt(filepath, data, delimiter='\t')  #Saves corrected MH data in subfolder
    
print("All files were split into down and upsweep and data was saved in subfolder.")